// (/note showlist)
// (/note showgallery)
// (/note show note_name:[string] note_id:[string])
// (/note new)
// (/note edit note_name:[string] note_id:[string])
// (/note settings note_name:[string] note_id:[string])