// (/server intro edit)
// (/server intro show)
// (/server trigger edit)
// (/server trigger show)
// (/server trigger add name:[string])
// (/server trigger add name:[string] group:[string])
// (/server trigger add group:[string])
// (/server settings)
// (/server admin addrole:roleID removerole:roleID addmember:roleID removemember:roleID)
// (/server settings)
