// (/server intro edit)
// (/server intro show)
// (/server trigger edit)
// (/server trigger show)
// (/server trigger add name:[string])
// (/server trigger add name:[string] group:[string])
// (/server trigger add group:[string])
// (/server send {option: [trigger, intro]})
// (/server send {option: [trigger, intro]} channel:[channel])
// (/server settings)
// (/server admin addrole:roleID removerole:roleID addmember:roleID removemember:roleID)
// (/server set userIntroChannel:[channel] userTriggerChannel:[channel])
